= PML Rouge Lexer
Tristano Ajmone <tajmone@gmail.com>
:source-highlighter: rouge
:rouge-style: pml-test-theme
:toclevels: 5
:toc: left
:idprefix:
:experimental: true
:icons: font
:linkattrs: true
:reproducible: true
:sectanchors:

In this document we'll focus on specific elements of the PML syntax, one element per section, in order to check that they are rendered properly by the lexer and theme.
For each element, we'll also mention it's Rouge token name and its corresponding HTML/CSS class.

For better visual inspection, we'll be using a custom Rouge theme here, designed to cover all the syntax elements of the PML lexer.

// CUSTOM ATTRIBUTES:
:manURL: https://www.pml-lang.dev/docs/reference_manual/index.html#
:manRef: PML Reference Manual »
:guideURL: https://www.pml-lang.dev/docs/user_manual/index.html#
:guideRef: PML User Manual »

== Comments

[horizontal]
Lexer class :: `Comment::Multiline`
CSS class   :: `cm`

link:{manURL}ch__12[PML comments^,title="{manRef} Comments"]
are node blocks which can be nested to any level.
The node has no attributes, and any PML nodes (other than further comment blocks) inside comments will be ignored by the PML Converter.

.Comments Examples
[source,pml]
---------------------------------------
Hello [- comment -] world.

All comments are block comments [-
  Comment block.
  Spanning multiple lines
  -] in PML.

Comments are nestable [- outer comment [- nested comment -] -] in PML.
---------------------------------------

Let's test that comments nesting is working correctly:

.Nested Comments Test
[source,pml]
---------------------------------------
normal text [-[--] comment -] normal text

normal text [-[--] comment
still a comment
because the outer comment was never closed!
---------------------------------------


== Escapes

[horizontal]
Lexer class :: `Literal::String::Escape` (short: `Str::Escape`)
CSS class   :: `se`


link:{guideURL}ch__10[PML escape sequences^,title="{guideRef} Escaping Reserved Characters"]
are achieved by preceding with a ``\`` the reserved characters ``[``,  ``]``,  ``=`` and  ``\``, or a ``{quot}`` inside double-quoted strings.


.Escapes Example
[source,pml]
---------------------------------------
File path \= C:\\tests\\example.txt

Instead of writing \\, we have to write \\\\

Instead of writing \[, we have to write \\\[
---------------------------------------


== Constant Parameter

[horizontal]
Lexer class :: `Name::Constant`
CSS class   :: `no`

link:{manURL}node_const[Constant parameters^,title="{manRef} Constant Parameter"]
are a powerful substitution mechanism.

.Parameters Example
[source,pml]
---------------------------------------
[const examples_root = http://www.example.com/project/source_code/examples]

Here are two examples:

[link url=<<examples_root>>/ex1.html text=example 1]

[link url=<<examples_root>>/ex2.html text=example 2].
---------------------------------------

Custom IDs definitions in PML are limited to the RegEx pattern ``[a-zA-Z][a-zA-Z0-9_]*``, and the Rouge lexer will mark as `Error` any references to invalid parameter IDs:

.Invalid Parameter ID Example
[source,pml]
---------------------------------------
[const invalid.param.id = something]

Let me tell you <<invalid.param.id>>
---------------------------------------

[NOTE]
===========
In the future PML will allow custom IDs to be names as in the XML standard.
===========

// EOF //
